
enable:

disable:

override_nonhours:
  fields:
    hours:
      required: true
      example: 2

scheduler_set:
  fields:
    charge_amount:
      required: true
      example: 7.2
    departure_time:
      required: true
      example: 2022-06-02 07:00
    schedule_starttime:
      example: 2022-06-01 18:00
    override_settings:
      example: False

scheduler_cancel:

override_charge_amount:
  fields:
    desired_charge_amount:
      required: true
      example: 10